project:
  type: website
  output-dir: docs

website:
  title: "YOUR NAME"
  #site-url: https://kkalkunte.github.io/kk_notebook/
  #google-analytics: # something to come here
  #site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  navbar:
    logo: headshots/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lab Notebook"
        href: notebook.qmd
      - text: "Lab Handbook"
        href: https://alcalalab.github.io/resources/
 #    right:
 #     - icon: github
 #       href: YOUR GITHUB
  
  page-footer:
    left: |
      Â© 2026 Your Name

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    link-external-icon: false

execute:
  freeze: auto



